### ISSUE TITLE
✨ [Feat] socket 초기화 메소드 및 관련 event 구현

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-socket-server#16]
## 📝 기능 개요

socket 초기화 메소드 및 관련 event 구현

## ✅ Todo
- [x] 채팅방 uuid 조회 및 room join 구현
- [x] 8080서버 api 요청 시 에러 응답에 대한 예외 처리
- [x] 친구 목록 조회 및 event emit, listener 구현
