### ISSUE TITLE
✨ [Feat] 사용자가 매칭에 들어올 경우 초기 설정

### ISSUE THREAD

**Issue by rimi3226** [Gamegoo-repo/Gamegoo-socket-server#17]
## 📝 기능 개요
사용자가 매칭 풀에 들어올 경우 NodeJS API 로직 구현

## ✅ Todo
- [x] 해당 정보를 소켓에 저장하기
- [x] 클라이언트에서 listen한거 확인하기
- [x] 프론트 퍼블리시
- [x] 게임 모드에 따라서 매칭 room  join

### 📚 Remarks
API 응답이 매칭 성공일 경우 -> 상대 member_id를 받아서 chatroom으로 연동시킬 예정 (다른 이슈에서 진행)
API 응답이 매칭 대기일 경우 -> 냅두기
