### ISSUE TITLE
✨ [Feat] socket disconnect 및 로그아웃 관련 event 구현

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-socket-server#24]
## 📝 기능 개요

socket disconnect 관련 event 구현

## ✅ Todo
- [x] friend-offline event emit & listener
- [x] socket disconnect event listener
- [ ] 로그아웃 버튼 클릭 시 8080, 3000서버에 로그아웃 요청 전송
- [x] /logout api 구현
