### ISSUE TITLE
✨ [Feat] 채팅방 목록 조회 및 채팅방 입장 기능 구현

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-socket-server#26]
## 📝 기능 개요

채팅방 목록 조회 및 채팅방 입장 기능 구현

## ✅ Todo
- [x] 8080서버로 채팅방 목록 조회 api 요청
- [x] 채팅방 목록 화면 렌더링
- [x] 8080서버로 채팅방 입장 api 요청
- [x] 채팅방 내부 화면 렌더링
- [ ] flow uml 수정
