### ISSUE TITLE
✨ [Feat] 알림창 및 채팅방 내부 팝업 화면 구현

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-socket-server#37]
## 📝 기능 개요

알림창 및 채팅방 내부 팝업 화면 구현

## ✅ Todo
- [x] 알림창 닫기 버튼 추가
- [x] 채팅방 내부 팝업 버튼 추가
- [x] 채팅방 나가기, 친구 추가, 차단 메뉴바 추가
