### ISSUE TITLE
✨ [Feat] 채팅방 API 변경 반영 및 친구목록, 채팅방 입장/시작 관련 로직 추가

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-socket-server#39]
## 📝 기능 개요

채팅방 API 변경 반영 및 친구목록, 채팅방 입장/시작 관련 로직 추가

## ✅ Todo
- [x] 채팅 읽음 처리 API http 메소드 변경 반영 (GET -> PATCH)
- [x] 채팅방 나가기 API http 메소드 변경 반영 (GET -> PATCH)
- [x] 채팅방 입장/시작 시, 상대가 나를 차단한 경우 메시지 전송 불가하도록 화면 추가
- [x] 채팅방 입장/시작 시, 상대와 내가 친구인지 여부에 따른 메뉴 팝업 버튼 생성
- [x] 채팅방 입장/시작 시, 상대와 내가 친구관계일 때만 채팅방 헤더에 온라인 여부 표시되도록
- [x] 친구 목록에 즐겨찾기 여부 표시 추가
- [x] 친구 목록에서 별 아이콘 클릭 시 즐겨찾기 설정/해제 API 연동
