### ISSUE TITLE
✨ [Feat] 채팅방 메뉴팝업 API 연동 및 친구,채팅방 목록 새로고침 버튼 추가

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-socket-server#41]
## 📝 기능 개요

채팅방 메뉴팝업 API 연동 및 친구,채팅방 목록 새로고침 버튼 추가

## ✅ Todo
- [x] 메뉴 팝업 버튼 API 연동 - 친구 삭제 API
- [x] 메뉴 팝업 버튼 API 연동 - 친구 요청 전송 API
- [x] 메뉴 팝업 버튼 API 연동 - 회원 차단 API
- [x] 메뉴 팝업에서 회원 차단 시, api 요청 보낸 후에 채팅방 화면 초기화 및 채팅방 목록에서 해당 채팅방 삭제
- [x] 친구 목록 새로고침 버튼 추가
- [x] 채팅방 목록 새로고침 버튼 추가
