### ISSUE TITLE
✨ [Feat] 채팅방 room join API 구현 및 room leave 구현

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-socket-server#43]
## 📝 기능 개요

채팅방 room join API 및 room leave 구현

## ✅ Todo
- [x] 채팅방 room join API 구현
- [x] room join 후 해당 socket에게 "joined-new-chatroom" event emit
- [x] "joined-new-chatroom" event listener 구현
- [x] 채팅방 나가기, 차단하기 버튼 클릭 시 "exit-chatroom" event emit
- [x] "exit-chatroom" event listener 구현
