### ISSUE TITLE
✨ [Feat] Matching Found Emit 발생 시 클라이언트에서 온 대답을 바탕으로 Emit 보내기

### ISSUE THREAD

**Issue by rimi3226** [Gamegoo-repo/Gamegoo-socket-server#56]
## 📝 기능 개요
Matching Found Emit 발생 시 클라이언트에서 온 대답을 바탕으로 Emit 보내기

## ✅ Todo
- [ ] (클라이언트) matching_found emit이 올 경우 매칭 다시하기 버튼 보여주기
- [ ] (클라이언트) 매칭 다시하기 버튼 10초안에 안누를 경우 3000으로 matching_success emit 보내기
- [ ] (클라이언트) 매칭 다시하기 버튼 10초안에 누를 경우 3000으로 isAgain=false와 함께 matching_failed 보내기

### 기획서 내용
- 매칭이 성공되고 자유 나가기 (10초 뒤) 사람이 유지 되었다면 자동적으로 실시간 채팅방을 만들어 소통이 가능할 수 있도록 유지한다.
- 매칭 되었을 때: 한쪽이 거절했을 경우 사용자에게 매칭 거절 팝업 화면을 보여준다 “아쉽게도 상대방과 매칭이 성사되지 못했어요. 계속해서 매칭을 시도하시겠습니까? 예/ 아니오”
- 매칭이 성립되지 않았을 때: 기존 정보대로 5분 매칭을 돌릴 수 있는 팝업화면을 제공한다 “계속해서 매칭을 시도하시겠습니까? 예/아니오”
- “예” 선택 시 기존의 조건 그대로 매칭을 다시 5분 진행, “아니오” 선택 시 매칭 종료 후 게시판에 같은 조건으로 글을 올린 사람을 데이터를 찾아 목록으로 보여줌
- 그래도 조건에 맞는 사람이 없음 -> 팝업창 노출(“조건에 맞는 사람이 없습니다. 게시판에 글을 작성할 수 있어요!”)
![image](https://github.com/user-attachments/assets/3df18ba8-e9f1-441b-9483-3dbd7eca529e)

### matching_found 이후 로직
1. (클라이언트) 매칭 성공 후 10초안에 안나가면 matching_success emit 하기
2. (클라이언트) 매칭 성공 후 나가기 누르면 양쪽 소켓에 matching_fail emit,
3. (NodeJS) matching_fail emit에서 소켓룸에서 제거, 모든 소켓의 priorityTree에서 제거,  isAgain == false일 경우, 클라이언트에게 계속해서 매칭 시도하겠냐고 묻는 emit 전송
4. (클라이언트) 계속해서 매칭을 시도하겠습니까? 화면 보여주기 
    4.1 매칭 시도 response :  O -> matching_started emit (방금 전 request와 동일하게)
    4.2 매칭 시도 response : X -> 게시판 필터링 API 불러와서 목록 보여주기
5. 두 번째 매칭일 경우 matching_success emit에 isAgain == true로 보내기. isAgain 여부 소켓에서 저장하기. 마지막 matching_fail에서 isAgain이 true일 경우 계속해서 매칭을 시도하겠냐고 묻지 않고, 게시판 필터링 API 불러오기
    5.1 게시판 필터링 API에서 사용자가 원하는 조건의 게시글이 있을 경우 "같은 조건으로 글을 올린 사람이 있어요!" 문구 보여주기
    5.2 게시판 필터링 API에서 사용자가 원하는 조건의 게시글이 없을 경우 "게시판에 글을 작성할 수 있어요!" 문구 보여주기
6. matching_success에서는 매칭 상태 변경 API(SUCCESS) 호출
7.  사용자가 중간에 나간 경우 매칭 상태 변경 API(QUIT) 호출, matching_fail에서 진행한 것과 동일하게 소켓 룸에서 제거, 모든 소켓의 priorityTree에서 제거
