### ISSUE TITLE
✨ [Feat] 테스트 수정사항 반영

### ISSUE THREAD

**Issue by rimi3226** [Gamegoo-repo/Gamegoo-socket-server#86]
## ✅ Todo
- [x]  retry priority 낮춰서 테스트해보기
- [x]  매칭 성공했을 때 quit 버튼 추가해서 테스트해보기
- [x]  매칭 found 이후 matching-success emit 안 올 경우 5초동안 기다리지 않고 2,3초만 기다리기 ( 둘 다 해보고 더 좋은 걸로 설정) - sender일 때 5초→3초, receiver일 때 3초→2초
- [ ]
