### ISSUE TITLE
✨ [Feat] 로그인 및 socket 연결 기능 구현

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-socket-server#9]
## 📝 기능 개요

클라이언트 로그인 구현
3000서버 로그인 API 구현
socket 연결 및 초기화 구현

## ✅ Todo
- [x] 클라이언트 로그인 구현
- [x] 3000서버 로그인 API 구현
- [x] socket 연결 및 초기화 구현
